Update sync_data_bucket.yml

diff --git a/.github/workflows/sync_data_bucket.yml b/.github/workflows/sync_data_bucket.yml
--- a/.github/workflows/sync_data_bucket.yml
+++ b/.github/workflows/sync_data_bucket.yml
@@ -10,21 +10,32 @@ on:
 
 jobs:
   sync-data:
-    # only run if upstream workflow succeeded
     if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
 
     runs-on: ubuntu-latest
+
+    env:
+      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+      HF_TOKEN: ${{ secrets.HF_TOKEN }}
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Debug workspace
+        run: ls -R
+
       - name: Install uv
         uses: astral-sh/setup-uv@v6
 
+      - name: Verify HF token exists
+        run: |
+          if [ -z "$HF_TOKEN" ]; then
+            echo "HF_TOKEN is missing"
+            exit 1
+          fi
+
       - name: Upload data folder to HF Space bucket
-        env:
-          HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: |
           uvx hf upload \
             e-zaline/power-plant-tracker \
